const express = require('express')
const router = express.Router()
const UserController = require('../app/controller/UserController')
const middlewareVerify = require('../app/middleware/UserMiddleware')
const multer = require('multer')
const upload = multer()

router.post('/login', UserController.index)
router.post('/create', UserController.create)
router.post('/updateStory',upload.none(), UserController.updateStory)
router.get('/profileByUserId/:userId', UserController.profileByUserId)
router.get('/profile', middlewareVerify, UserController.profile)
router.get('/:userId',  UserController.getName)
// router.get('/getAll', UserController.findAll)
module.exports = router