const express = require('express')
const router = express.Router()
const {UserController} = require('../app/controller/UserController')
const middlewareVerify = require('../app/middleware/UserMiddleware')
const multer = require('multer')
const upload = multer()

router.get('/checkOnlineUser', middlewareVerify, new UserController().checkOnlineUser)
router.post('/login', new UserController().index)
router.post('/create', new UserController().create)
router.post('/updateStory',upload.none(), new UserController().updateStory)
router.get('/profileByUserId/:userId', new UserController().profileByUserId)
router.get('/profile', middlewareVerify, new UserController().profile)
router.get('/:userId',  new UserController().getName)
// router.get('/getAll', UserController.findAll)
module.exports = router